name: SonarCloud
on:
  workflow_run:
    workflows: ["Build and analyze"]
    types:
      - completed

jobs:
  analyze:
    name: Analyze code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install sonar-scanner
        uses: SonarSource/sonarcloud-github-c-cpp@v2
      - name: Run sonar-scanner
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          sonar-scanner
